# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# # These are for the Arduino Nano
# BOARD_TAG   = nano
# MCU   = atmega328p
# ARDUINO_PORT = /dev/ttyUSB0

# These are for the Arduino Uno
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0

AVRDUDE_ARD_BAUDRATE=115200
CXXFLAGS_STD = -std=c++11
CXXFLAGS = -Wall -Wextra -pedantic
include ./Arduino-Makefile/Arduino.mk
