# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# --- mega2560 or uno ide 1.0
# BOARD_TAG    = mega2560
BOARD_TAG   = nano
MCU   = atmega328p
# BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyUSB0
# ARDUINO_PORT = /dev/ttyACM0
AVRDUDE_ARD_BAUDRATE=115200
CXXFLAGS_STD = -std=c++11
CXXFLAGS = -Wall -Wextra -pedantic
include ./Arduino-Makefile/Arduino.mk
